# Generated by Django 3.2.12 on 2022-05-24 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_column='movie_Name', max_length=100)),
                ('genre', models.CharField(db_column='genre', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='userData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='Name', max_length=30)),
                ('email', models.EmailField(db_column='Email', max_length=254)),
                ('mobile', models.IntegerField(db_column='Mobile')),
                ('domain', models.CharField(db_column='Domain', max_length=100)),
            ],
        ),
    ]
